In [1]:
import pandas as pd
import numpy as np
from numpy import std, absolute, mean
import seaborn as sns
import sklearn as sk
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import datetime
import tensorflow as tf
from tensorflow.python.client import device_lib #GPU Check
import tensorflow.keras #keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential, Input, Model
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input, Add, Activation, ZeroPadding2D
from tensorflow.keras.layers import LSTM, BatchNormalization, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint #use for early stopping
from tensorflow.keras.initializers import glorot_uniform, he_uniform #to initialize random weights for filters
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image as image_utils
from tensorflow.keras.applications.imagenet_utils import preprocess_input, decode_predictions
from tensorflow.keras.models import Sequential, Model, load_model
from tensorflow.keras import utils
from tensorflow.keras.utils import get_file, plot_model, to_categorical, model_to_dot

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
%pwd

'/Users/melekmizher/Desktop/NLP with Disaster Tweets'

In [4]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [5]:
train.head()
test.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

   id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [6]:
train

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
...,...,...,...,...,...
7608,10869,NaN,NaN,Two giant cranes holding a bridge collapse int...,1
7609,10870,NaN,NaN,@aria_ahrary @TheTawniest The out of control w...,1
7610,10871,NaN,NaN,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...,1
7611,10872,NaN,NaN,Police investigating after an e-bike collided ...,1
7612,10873,NaN,NaN,The Latest: More Homes Razed by Northern Calif...,1

In [7]:
train.keyword.value_counts()

fatalities               45
deluge                   42
armageddon               42
sinking                  41
damage                   41
                         ..
forest%20fire            19
epicentre                12
threat                   11
inundation               10
radiation%20emergency     9
Name: keyword, Length: 221, dtype: int64

In [8]:
train.location.value_counts()

USA                    104
New York                71
United States           50
London                  45
Canada                  29
                      ...
MontrÌ©al, QuÌ©bec       1
Montreal                 1
ÌÏT: 6.4682,3.18287      1
Live4Heed??              1
Lincoln                  1
Name: location, Length: 3341, dtype: int64

# Lexical Analysis

In [9]:
import re

In [10]:
def cleanText(text):
    text = re.sub(r'@[A-Za-z0-9]+', '', text)
    text = re.sub(r'#', '', text)
    text = re.sub(r'&amp;', ' and ', text)
    text = re.sub(r'https?:\/\/\S+', '', text)
    text = re.sub(r'RT[\s]+', '', text)
    text = re.sub(r"can't", 'can not', text)
    text = re.sub(r"n't", ' not', text)
    text = re.sub(r"\s'\s?|'\s", ' ', text)
    text = re.sub(r"'s", ' is', text)
    text = re.sub(r"'re", ' are', text)
    text = re.sub(r"w\/", 'with ', text)
    text = re.sub(r"'ve", ' have', text)
    text = re.sub(r"'m", ' am', text)
    text = re.sub(r"'ll", ' will', text)
    text = re.sub(r"-", '', text)
    text = re.sub(r"!", '', text)
    text = re.sub(r",", '', text)
    text = re.sub(r";", '', text)
    text = re.sub(r":", '', text)
    text = re.sub(r"_", '', text)
    text = re.sub(r"\|", '', text)
    text = re.sub(r"\@", '', text)
    text = re.sub(r"/\n", '', text)
    text = re.sub(r"\?", '', text)
    text = re.sub(r"[^A-Za-z0-9]", " ", text)
    return text

In [11]:
train['text'] = train['text'].apply(cleanText)
train['text'] = train['text'].str.lower()

In [12]:
test['text'] = test['text'].apply(cleanText)
test['text'] = test['text'].str.lower()

In [13]:
test

,id,keyword,location,text
0,0,NaN,NaN,just happened a terrible car crash
1,2,NaN,NaN,heard about earthquake is different cities sta...
2,3,NaN,NaN,there is a forest fire at spot pond geese are ...
3,9,NaN,NaN,apocalypse lighting spokane wildfires
4,11,NaN,NaN,typhoon soudelor kills 28 in china and taiwan
...,...,...,...,...
3258,10861,NaN,NaN,earthquake safety los angeles safety faste...
3259,10865,NaN,NaN,storm in ri worse than last hurricane my city...
3260,10868,NaN,NaN,green line derailment in chicago
3261,10874,NaN,NaN,meg issues hazardous weather outlook hwo
3262,10875,NaN,NaN,cityofcalgary has activated its municipal emer...

In [14]:
pd.options.display.max_rows = 500

In [15]:
#pd.describe_option('display')

In [16]:
pd.describe_option('display.max_colwidth')
pd.set_option('display.max_colwidth', 110)

display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]

In [17]:
train.text.head(500)

0                                               our deeds are the reason of this earthquake may allah forgive us all
1                                                                             forest fire near la ronge sask  canada
2      all residents asked to shelter in place are being notified by officers  no other evacuation or shelter in ...
3                                                    13000 people receive wildfires evacuation orders in california
4                             just got sent this photo from ruby alaska as smoke from wildfires pours into a school
5         rockyfire update    california hwy  20 closed in both directions due to lake county fire  cafire wildfires
6                       flood disaster heavy rain causes flash flooding of streets in manitou colorado springs areas
7                                                       i am on top of the hill and i can see a fire in the woods
8                                   there is an emergency evacuation happening now in the building across the street
9                                                              i am afraid that the tornado is coming to our area
10                                                                       three people died from the heat wave so far
11     haha south tampa is getting flooded hah wait a second i live in south tampa what am i gonna do what am i g...
12                                         raining flooding florida tampabay tampa 18 or 19 days  i have lost count
13                                                                             flood in bago myanmar we arrived bago
14                                                           damage to school bus on 80 in multi car crash breaking
15                                                                                                    what is up man
16                                                                                                     i love fruits
17                                                                                                  summer is lovely
18                                                                                                 my car is so fast
19                                                                                            what a goooooooaaaaaal
20                                                                                            this is ridiculous
21                                                                                                  london is cool
22                                                                                                       love skiing
23                                                                                              what a wonderful day
24                                                                                                          looooool
25                                                                                  no way   i can not eat that shit
26                                                                                              was in nyc last week
27                                                                                                love my girlfriend
28                                                                                                          cooool
29                                                                                                 do you like pasta
30                                                                                                           the end
31                                                                                         wholesale markets ablaze
32                                                                          we always try to bring the heavy  metal
33                                                         africanbaze breaking newsnigeria flag set ablaze in aba
34                                                                                 crying out for more set me ablaze
35                                                            on plus side look at the sky last night it was ablaze
36      mufc they have built so much hype around new acquisitions but i doubt they will set the epl ablaze this s...
37                                                                                  inec office in abia set ablaze
38     barbados bridgetown jamaica     two cars set ablaze santa cruz     head of the st elizabeth police superin...
39                                                                                             ablaze for you lord d
40                                                                                          check these out     nsfw
41                                                   on the outside you are ablaze and alive but you are dead inside
42     had an awesome time visiting the cfc head office the ancop site and ablaze  thanks to tita vida for taking...
43                                                                                         soooo pumped for ablaze
44                                             i wanted to set chicago ablaze with my preaching    but not my hotel
45                                         i gained 3 followers in the last week  you know your stats and grow with
46                                        how the west was burned thousands of wildfires ablaze in california alone
47                                                   building the perfect tracklist to life leave the streets ablaze
48                                                                                          check these out     nsfw
49     first night with retainers in  it is quite weird  better get used to it i have to wear them every single n...
50                                                                deputies man shot before brighton home set ablaze
51                                                             man wife get six years jail for setting ablaze niece
52                         santa cruz     head of the st elizabeth police superintendent lanford salmon has r
53                                          police arsonist deliberately set black church in north carolina  ablaze
54                          noches elbestia sanchez happy to see my teammates and training hard  goodnight gunners
55     kurds trampling on turkmen flag later set it ablaze while others vandalized offices of turkmen front in di...
56                                        truck ablaze  r21  voortrekker ave  outside or tambo intl  cargo section
57               set our hearts ablaze and every city was a gift and every skyline was like a kiss upon the lips
58     they sky was ablaze tonight in los angeles  i am expecting ig and fb to be filled with sunset shots if i k...
59                        how the west was burned thousands of wildfires ablaze in california alone  climate energy
60                              revel in yours wmv videos by means of mac farewell ablaze wmv en route to dvd gtxrwm
61     progressive greetings  in about a month students would have set their pens ablaze in the torch publication...
62                                         rene ablaze  and  jacinta  secret 2k13  fallen skies edit   mar 30 2013
63      steve these fires out here are something else california is a tinderbox  and this clown was setting my ho...
64                                                            nowplaying rene ablaze  and  ian buff  magnitude   edm
65                                                                            huge fire at wholesale markets ablaze
66                                     what time does your talk go until i do not know if i can make it due to work
67      i can not have kids cuz i got in a bicycle accident  and  split my testicles  it is impossible for me to ...
68                                         accident on i24 w nashvilletraffic  traffic moving 8m slower than usual
69                 accident center lane blocked in santaclara on us101 nb before great america pkwy bayarea traffic
70            had a personalinjury accident this summer read our advice  and  see how a solicitor can help otleyhour
71                        stlouis caraccidentlawyer speeding among top causes of teen accidents   car accident tee
72     reported motor vehicle accident in curry on herman rd near stephenson involving an overturned vehicle  ple...
73                                                                               bigrigradio live accident awareness
74                          i77 mile marker 31 south mooresville  iredell vehicle accident ramp closed at 8 6 118 pm
75                                                                sleeping pills double your risk of a car accident
76                                                                        by accident they knew what was gon happen
77                                                 traffic accident n cabrillo hwy magellan av mir  08 06 15 110358
78                     i77 mile marker 31 to 40 south mooresville  iredell vehicle accident congestion at 8 6 118 pm
79                        the pastor was not in the scene of the accident      who was the owner of the range rover
80     mom we did not get home as fast as we wished  me why is that mom there was an accident and some truck spil...
81                 i was in a horrible car accident this past sunday  i am finally able to get around  thank you god
82                                    can wait to see how pissed donnie is when i tell him i was in another accident
83                           truckcrash overturns on fortworth interstate  click here if you have been in a crash gt
84                                                           accident in ashville on us 23 sb before sr 752 traffic
85     carolina accident motorcyclist dies in i540 crash with car that crossed median a motorcycle rider travelin...
86                                                    fyi cadfyi accident property damagenhs999 piner rd horndale dr
87     naayf first accident in years  turning onto chandanee magu from near mma  taxi rammed into me while i was ...
88     accident left lane blocked in manchester on rt 293 nb before eddy rd stop and go traffic back to nh3a dela...
89                                                                     accident property damage piner rd horndale dr
90                                                                                               it was an accident
91                                                              fyi cadfyi accident property damagewpd1600 s 17th st
92                                               8 6 201509 pm traffic accident no injury at 2781 willis foreman rd
93                                                          aashiqui actress anu aggarwal on her nearfatal accident
94                                                                                        suffield alberta accident
95     9 mile backup on i77 south   accident blocking the right 2 lanes at exit 31 langtree rd   consider nc 115 ...
96     has an accident changed your life we will help you determine options that can financially support life car...
97     breaking there was a deadly motorcycle car accident that happened to hagerstown today  i will have more de...
98                                                                      were you marinading it or was it an accident
99               only had a car for not even a week and got in a fucking car accident    mfs can not fucking drive
100                         bahrain police had previously died in a road accident they were not killed by explosion
101    i still have not heard church leaders of kenya coming forward to comment on the accident issue and discipl...
102                                                                            delo scuf ps live and the game    cya
103     the man who can drive himself further once the effort gets painful is the man who will win   roger bannister
104                                       320  ir  icemoon  aftershock       dubstep trapmusic dnb edm dance ices
105                                          there is no victory at bargain basement prices  dwight david eisenhower
106                                       320  ir  icemoon  aftershock       dubstep trapmusic dnb edm dance ices
107                                                              nobody remembers who came in second  charles schulz
108    delo im speaking from someone that is using a scuf on xb1 most of them people will end up getting on for p...
109                                              the harder the conflict the more glorious the triumph  thomas paine
110                                growingupspoiled going clay pigeon shooting and crying because of the aftershock
111                                                     so i guess no one actually wants any free aftershock tc
112    aftershock was the most terrifying best roller coaster i have ever been on   disclaimer  i have been on ve...
113                                                                                                      aftershock
114                                       320  ir  icemoon  aftershock       dubstep trapmusic dnb edm dance ices
115                                       320  ir  icemoon  aftershock       dubstep trapmusic dnb edm dance ices
116                                       320  ir  icemoon  aftershock       dubstep trapmusic dnb edm dance ices
117                                                                       i am seeing them and issues at aftershock
118                                       320  ir  icemoon  aftershock       dubstep trapmusic dnb edm dance ices
119                                       320  ir  icemoon  aftershock       dubstep trapmusic dnb edm dance ices
120    wisdomwed bonus  5 minute daily habits that could really improve your life  how many do you already do lif...
121             aftershock protect yourself and profit in the next global financial meltdown by david wiedemer http
122    that moment when you get on a scary roller coaster and the guy behind you is just screaming bloody murder ...
123                                                                aftershock      2010  full    streaming  youtube
124                         gt gt  15 aftershock  protect yourself and profit in the next global financial    book
125    sometimes you face difficulties not because you are doing something wrong but because you are doing someth...
126     the only thing that stands between you and your dream is the will to try and the belief that it is actual...
127                                praise god that we have ministry that tells it like it is now wdyouth biblestudy
128     remembering that you are going to die is the best way i know to avoid the trap of thinking you have somet...
129                                                    tried orange aftershock today  my life will never be the same
130                                                                                                    i love you bb
131                                                                                                      aftershock
132    aftershock back to school kick off was great  i want to thank everyone for making it possible  what a grea...
133            people who say it cannot be done should not interrupt those who are doing it      george bernard shaw
134                                     the first man gets the oyster the second man gets the shell  andrew carnegie
135                                          anyone need a p u tonight i play hybrid slayer ps4 eu  hmu    kotc  org
136    experts in france begin examining airplane debris found on reunion island french air accident experts o   ...
137    strict liability in the context of an airplane accident pilot error is a common component of most aviation...
138                                             your lifetime odds of dying from an airplane accident are 1 in 8015
139    experts in france begin examining airplane debris found on reunion island french air accident experts on w...
140                            awwww they are on an airplane accident and they are gonna die what a cuties  good job
141         family members of osama bin laden have died in an airplane accident how ironic  mhmmm gov shit i suspect
142                                                                     man goes into airplane engine accident  via
143                                                     horrible accident  man died in wings of airplane  29072015
144    a cessna airplane accident in ocampo coahuila mexico on july 29 2015 killed four men including a state of ...
145                                           horrible accident man died in wings airplane  29072015  watchthevideo
146    experts in france begin examining airplane debris found on reunion island  french air accident experts on ...
147    experts in france begin examining airplane debris found on reunion island french air accident experts on w...
148                      kca votejkt48id mbataweel rip binladen family members who killed in an airplane is accident
149                                          i almost sent my coworker nudes on accident thank god for airplane mode
150            that or they might be killed in an airplane accident in the night a car wreck politics at it is best
151    experts in france begin examining airplane debris found on reunion island french air accident experts on  ...
152                   this is unbelievably insane  man airport airplane aircraft aeroplane runway accident freaky
153                                                   horrible accident   man died in wings of airplane   29072015
154                                                      horrible accident man died in wings of airplane  29072015
155                                           usama bin ladins family dead in airplane crash  naturally no accident
156             pilot dies in plane crash at car festival  via  crash aircraft airplane pilot death accident carfest
157                                                        strict liability in the context of an airplane accident
158    dtn brazil experts in france begin examining airplane debris found on reunion island french air accident e...
159    experts in france begin examining airplane debris found on reunion island french air accident experts on w...
160        horrible accident man died in wings of    airplane    29072015  wtf you can   t believe your eyes
161      nicole fletcher one of a victim of crashed airplane few times ago    the accident left a little bit trau...
162                                                            omg horrible accident man died in wings of airplane
163                               omg i do not believe this  rip bro airplane accident jetengine turbojet boing g90
164    experts in france begin examining airplane debris found on reunion island french air accident experts on w...
165                                                                                       i had a airplane accident
166                                             my phone looks like it was in a car ship airplane accident  terrible
167        statistically i am at more of risk of getting killed by a cop than i am of dying in an airplane accident
168                                                 airplane crashes on house in colombia 12 people die in accident
169                                                                          the shooting or the airplane accident
170    could a drone cause an airplane accident pilots worried about use of drones esp  in close vicinity of airp...
171    early wake up call from my sister begging me to come over  and  ride with her in the ambulance to the hosp...

In [18]:
from textblob import TextBlob
#Create a function to get the subjectivity
def getSubjectivity(twt):
    return TextBlob(twt).sentiment.subjectivity

In [19]:
df = train.text.apply(getSubjectivity)

In [20]:
import nltk

In [21]:
#nltk.download('punkt')
#nltk.download('wordnet')
#nltk.download('omw-1.4')
#nltk.download('stopwords')

In [22]:
train.text.head()

0                                             our deeds are the reason of this earthquake may allah forgive us all
1                                                                           forest fire near la ronge sask  canada
2    all residents asked to shelter in place are being notified by officers  no other evacuation or shelter in ...
3                                                  13000 people receive wildfires evacuation orders in california
4                           just got sent this photo from ruby alaska as smoke from wildfires pours into a school
Name: text, dtype: object

# Semantic Analysis - Removing Stop Words

In [23]:
from nltk.corpus import stopwords

In [24]:
from gensim.parsing.preprocessing import remove_stopwords

In [25]:
#stop_words = set(stopwords.words('english'))

"""def removeStopWords(tweet):
    filtered_sentence = []
    i = 0
    while i < len(tweet):
        for word in tweet:
            if word not in stop_words:
                filtered_sentence.append(word)
            i = i + 1
    return filtered_sentence"""

In [26]:
#train.col_lemma = train.col_lemma.apply(lambda x: [item for item in x if item not in stop_words])

In [27]:
train

,id,keyword,location,text,target
0,1,NaN,NaN,our deeds are the reason of this earthquake may allah forgive us all,1
1,4,NaN,NaN,forest fire near la ronge sask canada,1
2,5,NaN,NaN,all residents asked to shelter in place are being notified by officers no other evacuation or shelter in ...,1
3,6,NaN,NaN,13000 people receive wildfires evacuation orders in california,1
4,7,NaN,NaN,just got sent this photo from ruby alaska as smoke from wildfires pours into a school,1
...,...,...,...,...,...
7608,10869,NaN,NaN,two giant cranes holding a bridge collapse into nearby homes,1
7609,10870,NaN,NaN,ahrary the out of control wild fires in california even in the northern part of the state very troubling,1
7610,10871,NaN,NaN,m1 94 0104 utc 5km s of volcano hawaii,1
7611,10872,NaN,NaN,police investigating after an ebike collided with a car in little portugal ebike rider suffered serious n...,1
7612,10873,NaN,NaN,the latest more homes razed by northern california wildfire abc news,1

# Tokenization and Lemmatization

In [28]:
test.text

0                                                                                  just happened a terrible car crash
1                                                      heard about earthquake is different cities stay safe everyone
2                      there is a forest fire at spot pond geese are fleeing across the street i cannot save them all
3                                                                              apocalypse lighting  spokane wildfires
4                                                                       typhoon soudelor kills 28 in china and taiwan
                                                            ...
3258                                                          earthquake safety los angeles     safety fasteners xrwn
3259    storm in ri worse than last hurricane  my city and 3others hardest hit  my yard looks like it was bombed  ...
3260                                                                                green line derailment in chicago
3261                                                                      meg issues hazardous weather outlook  hwo
3262                                               cityofcalgary has activated its municipal emergency plan  yycstorm
Name: text, Length: 3263, dtype: object

In [29]:
from nltk.tokenize import word_tokenize

train.text = train.text.apply(word_tokenize)
train.text.head()

test.text = test.text.apply(word_tokenize)
test.text.head()

0                               [our, deeds, are, the, reason, of, this, earthquake, may, allah, forgive, us, all]
1                                                                    [forest, fire, near, la, ronge, sask, canada]
2    [all, residents, asked, to, shelter, in, place, are, being, notified, by, officers, no, other, evacuation,...
3                                          [13000, people, receive, wildfires, evacuation, orders, in, california]
4           [just, got, sent, this, photo, from, ruby, alaska, as, smoke, from, wildfires, pours, into, a, school]
Name: text, dtype: object

0                                                                        [just, happened, a, terrible, car, crash]
1                                          [heard, about, earthquake, is, different, cities, stay, safe, everyone]
2    [there, is, a, forest, fire, at, spot, pond, geese, are, fleeing, across, the, street, i, can, not, save, ...
3                                                                       [apocalypse, lighting, spokane, wildfires]
4                                                           [typhoon, soudelor, kills, 28, in, china, and, taiwan]
Name: text, dtype: object

In [30]:
from nltk.stem import WordNetLemmatizer

wnl = WordNetLemmatizer()

def lemmatize(s):
    s = [wnl.lemmatize(word) for word in s]
    return s

train = train.assign(text = train.text.apply(lambda x: lemmatize(x)))
train.text = train.text.squeeze()

test = test.assign(text = test.text.apply(lambda x: lemmatize(x)))
test.text = test.text.squeeze()

In [31]:
train.text.head(10)

0                                 [our, deed, are, the, reason, of, this, earthquake, may, allah, forgive, u, all]
1                                                                    [forest, fire, near, la, ronge, sask, canada]
2    [all, resident, asked, to, shelter, in, place, are, being, notified, by, officer, no, other, evacuation, o...
3                                            [13000, people, receive, wildfire, evacuation, order, in, california]
4             [just, got, sent, this, photo, from, ruby, alaska, a, smoke, from, wildfire, pours, into, a, school]
5    [rockyfire, update, california, hwy, 20, closed, in, both, direction, due, to, lake, county, fire, cafire,...
6          [flood, disaster, heavy, rain, cause, flash, flooding, of, street, in, manitou, colorado, spring, area]
7                                        [i, am, on, top, of, the, hill, and, i, can, see, a, fire, in, the, wood]
8                   [there, is, an, emergency, evacuation, happening, now, in, the, building, across, the, street]
9                                                   [i, am, afraid, that, the, tornado, is, coming, to, our, area]
Name: text, dtype: object

In [32]:
stop_words = stopwords.words('english')
stop_words.remove('not')

train.text = train.text.apply(lambda words: [word for word in words if word not in stop_words])

test.text = test.text.apply(lambda words: [word for word in words if word not in stop_words])

In [33]:
train.head(5)
test.head(5)

,id,keyword,location,text,target
0,1,NaN,NaN,"[deed, reason, earthquake, may, allah, forgive, u]",1
1,4,NaN,NaN,"[forest, fire, near, la, ronge, sask, canada]",1
2,5,NaN,NaN,"[resident, asked, shelter, place, notified, officer, evacuation, shelter, place, order, expected]",1
3,6,NaN,NaN,"[13000, people, receive, wildfire, evacuation, order, california]",1
4,7,NaN,NaN,"[got, sent, photo, ruby, alaska, smoke, wildfire, pours, school]",1

,id,keyword,location,text
0,0,NaN,NaN,"[happened, terrible, car, crash]"
1,2,NaN,NaN,"[heard, earthquake, different, city, stay, safe, everyone]"
2,3,NaN,NaN,"[forest, fire, spot, pond, goose, fleeing, across, street, not, save]"
3,9,NaN,NaN,"[apocalypse, lighting, spokane, wildfire]"
4,11,NaN,NaN,"[typhoon, soudelor, kill, 28, china, taiwan]"

# Full Cross-Validation Format Setup

In [34]:
import spacy, torch, transformers
from transformers import BertModel, BertTokenizer, TFBertModel, TFBertForSequenceClassification, BertConfig, AdamW, get_linear_schedule_with_warmup

In [35]:
train.text = train.text.apply(lambda x : " ".join(x))

In [36]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=1000, split=' ') 
tokenizer.fit_on_texts(train['text'].values)
X_train = tokenizer.texts_to_sequences(train['text'].values)
X_train = pad_sequences(X_train, maxlen=15)

In [37]:
X_test = tokenizer.texts_to_sequences(test['text'].values)
X_test = pad_sequences(X_test, maxlen=15)

In [38]:
pd.DataFrame(X_train).head(5)

   0   1   2   3   4   5   6   7   8    9    10   11   12   13   14
0   0   0   0   0   0   0   0   0   0    0    0  462  165   67    6
1   0   0   0   0   0   0   0   0   0    0    0  112    3  153  589
2   0   0   0   0   0   0   0   0   0  463  332  166  463  333  964
3   0   0   0   0   0   0   0   0   0    0   12   79  166  333   33
4   0   0   0   0   0   0   0   0   0    0   31  110  190   79  104

In [39]:
pd.DataFrame(X_test).head(5)

   0   1   2   3   4   5   6   7    8   9    10   11   12   13   14
0   0   0   0   0   0   0   0   0    0   0    0    0  777   46   32
1   0   0   0   0   0   0   0   0    0   0  388  165  105  433  146
2   0   0   0   0   0   0   0   0  112   3  638  736  449    1  259
3   0   0   0   0   0   0   0   0    0   0    0    0    0  390   79
4   0   0   0   0   0   0   0   0    0   0    0  414  583  108  252

# #1 LSTM Build.

In [40]:
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D

model = Sequential()
model.add(Embedding(500, 120, input_length = X_train.shape[1]))
model.add(SpatialDropout1D(0.4))
model.add(LSTM(176, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 15, 120)           60000

 spatial_dropout1d (SpatialD  (None, 15, 120)          0
 ropout1D)

 lstm (LSTM)                 (None, 176)               209088

 dense (Dense)               (None, 1)                 177

=================================================================
Total params: 269,265
Trainable params: 269,265
Non-trainable params: 0
_________________________________________________________________
None

2022-05-30 00:31:03.690562: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [41]:
from sklearn.model_selection import train_test_split

train_valid, test_valid = train_test_split(X_train, random_state=42, train_size=0.8)
print(train_valid.shape)
print(test_valid.shape)

(6090, 15)
(1523, 15)

In [42]:
y_train_valid, y_test_valid = train_test_split(train.target, random_state=42, train_size=0.8)

In [43]:
train_valid[0:5]
test_valid[0:5]
y_train_valid.head(5)
y_test_valid.head(5)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,  64, 402, 144,  36,
        987, 177],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 368,
        380, 145],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 491,   6, 382, 203,
        291, 618],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 341, 308, 649,
        175, 111],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 420, 407,
        371, 338]], dtype=int32)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   8,  72,
        130, 303],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  92,  31,
        349,  53],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  22],
       [  0,   0,   0, 740,  34, 104,   2, 127,  62, 425, 146, 515, 450,
        127, 172],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 302, 201, 718,
         10,  47]], dtype=int32)

4996    1
3263    0
4907    1
2855    1
4716    0
Name: target, dtype: int64

2644    1
2227    0
5448    1
132     0
6845    0
Name: target, dtype: int64

In [44]:
batch_size=10
model.fit(train_valid, y_train_valid, epochs = 10, batch_size=batch_size, validation_data =(test_valid, y_test_valid) , verbose = 'auto')

Epoch 1/10

InvalidArgumentError:  indices[0,6] = 906 is not in [0, 500)
	 [[node sequential/embedding/embedding_lookup
 (defined at /opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/layers/embeddings.py:189)
]] [Op:__inference_train_function_3027]

Errors may have originated from an input operation.
Input Source operations connected to node sequential/embedding/embedding_lookup:
In[0] sequential/embedding/embedding_lookup/1768:
In[1] sequential/embedding/Cast:

Operation defined at: (most recent call last)
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/runpy.py", line 191, in _run_module_as_main
>>>     msg = "%s: %s" % (sys.executable, exc)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/runpy.py", line 75, in _run_code
>>>     fname = mod_spec.origin
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/ipykernel_launcher.py", line 12, in <module>
>>>     if sys.path[0] == "":
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/traitlets/config/application.py", line 844, in launch_instance
>>>     app = cls.instance(**kwargs)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 697, in start
>>>     from ipykernel.trio_runner import TrioRunner
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 195, in start
>>>     old_loop = None  # type: ignore
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/asyncio/base_events.py", line 594, in run_forever
>>>     old_agen_hooks = sys.get_asyncgen_hooks()
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
>>>     event_list = self._selector.select(timeout)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/asyncio/events.py", line 80, in _run
>>>     self._context.run(self._callback, *self._args)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 502, in dispatch_queue
>>>     await self.process_one()
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 488, in process_one
>>>     t, dispatch, args = self.msg_queue.get_nowait()
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 375, in dispatch_shell
>>>     return
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 693, in execute_request
>>>     metadata = self.init_metadata(parent)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 355, in do_execute
>>>     preprocessing_exc_tuple=preprocessing_exc_tuple,
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 528, in run_cell
>>>     return super().run_cell(*args, **kwargs)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2863, in run_cell
>>>     result = self._run_cell(
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2885, in _run_cell
>>>     raw_cell,
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
>>>     coro.send(None)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3080, in run_cell_async
>>>     except self.custom_exceptions as e:
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3277, in run_ast_nodes
>>>     elif interactivity == 'all':
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3366, in run_code
>>>     if async_:
>>>
>>>   File "/var/folders/5m/ct1bwh6d20bfbgg2x0908mjm0000gn/T/ipykernel_76012/2712668370.py", line 2, in <cell line: 2>
>>>     model.fit(train_valid, y_train_valid, epochs = 10, batch_size=batch_size, validation_data =(test_valid, y_test_valid) , verbose = 'auto')
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 60, in error_handler
>>>     return fn(*args, **kwargs)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/engine/training.py", line 1168, in fit
>>>     y=y,
>>>
>>>   File "/var/folders/5m/ct1bwh6d20bfbgg2x0908mjm0000gn/T/__autograph_generated_filegewyq4el.py", line 12, in tf__train_function
>>>     retval_ = ag__.UndefinedReturnValue()
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/engine/training.py", line 866, in step_function
>>>     data = next(iterator)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/engine/training.py", line 860, in run_step
>>>     outputs = model.train_step(data)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/engine/training.py", line 807, in train_step
>>>     with tf.GradientTape() as tape:
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 60, in error_handler
>>>     return fn(*args, **kwargs)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1054, in __call__
>>>     self._clear_losses()
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 91, in error_handler
>>>     try:
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/engine/sequential.py", line 366, in call
>>>     'API.' % (type(inputs), inputs))
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/engine/functional.py", line 452, in call
>>>     inputs, training=training, mask=mask)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/engine/functional.py", line 573, in _run_internal_graph
>>>     tensor_dict[x_id] = [y] * tensor_usage_count[x_id]
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 60, in error_handler
>>>     return fn(*args, **kwargs)
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/engine/base_layer.py", line 1054, in __call__
>>>     self._clear_losses()
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 91, in error_handler
>>>     try:
>>>
>>>   File "/opt/anaconda3/envs/tensorflow/lib/python3.10/site-packages/keras/layers/embeddings.py", line 189, in call
>>>     if dtype != 'int32' and dtype != 'int64':
>>>

In [ ]:
y_pred = model.predict(X_test)

threshold =0.5
y_pred = np.where(y_pred > threshold, 1, 0)
y_pred = pd.DataFrame(y_pred)
y_pred.columns = ['target']

In [ ]:
y_pred.head(100)

In [ ]:
submission = pd.DataFrame(test.id)

In [ ]:
submission['target'] = y_pred

In [ ]:
submission = submission.set_index('id')

In [ ]:
submission.target.value_counts()

In [ ]:
submission.head(10)

In [ ]:
submission.to_csv("submission.csv")

# First Submission Kaggle Score: 0.75543

# #2 LSTM Build.

In [45]:
max_features = 3000
embed_dim = 32
lstm_out = 32
model = Sequential()
model.add(Embedding(max_features, embed_dim,input_length = X_train.shape[1]))
model.add(Dropout(0.2))
model.add(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.4))
model.add(Dense(1,activation='sigmoid'))
adam = tensorflow.keras.optimizers.Adam(learning_rate=0.002)
model.compile(loss = 'binary_crossentropy', optimizer=adam ,metrics = ['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_1 (Embedding)     (None, 15, 32)            96000

 dropout (Dropout)           (None, 15, 32)            0

 lstm_1 (LSTM)               (None, 32)                8320

 dense_1 (Dense)             (None, 1)                 33

=================================================================
Total params: 104,353
Trainable params: 104,353
Non-trainable params: 0
_________________________________________________________________
None

In [46]:
batch_size=64
model.fit(train_valid, y_train_valid, epochs = 5, batch_size=batch_size, validation_data =(test_valid, y_test_valid) , verbose = 'auto')

Epoch 1/5
96/96 [==============================] - 3s 17ms/step - loss: 0.5787 - accuracy: 0.6877 - val_loss: 0.4881 - val_accuracy: 0.7754
Epoch 2/5
96/96 [==============================] - 1s 13ms/step - loss: 0.4145 - accuracy: 0.8153 - val_loss: 0.4780 - val_accuracy: 0.7708
Epoch 3/5
96/96 [==============================] - 1s 14ms/step - loss: 0.3878 - accuracy: 0.8312 - val_loss: 0.4898 - val_accuracy: 0.7695
Epoch 4/5
96/96 [==============================] - 1s 14ms/step - loss: 0.3743 - accuracy: 0.8345 - val_loss: 0.5072 - val_accuracy: 0.7682
Epoch 5/5
96/96 [==============================] - 1s 14ms/step - loss: 0.3654 - accuracy: 0.8422 - val_loss: 0.5084 - val_accuracy: 0.7728

In [47]:
y_pred = model.predict(X_test)

threshold =0.5
y_pred = np.where(y_pred > threshold, 1, 0)
y_pred = pd.DataFrame(y_pred)
y_pred.columns = ['target']
submission = pd.DataFrame(test.id)
submission['target'] = y_pred
submission = submission.set_index('id')
submission.target.value_counts()

0    1981
1    1282
Name: target, dtype: int64

In [48]:
submission.to_csv("submission.csv")

# Second Submission Kaggle Score: 0.77290

# #3 LSTM Build

In [ ]:
max_features = 800
embed_dim = 64
lstm_out = 32
model = Sequential()
model.add(Embedding(max_features, embed_dim,input_length = X_train.shape[1]))
model.add(Dropout(0.2))
model.add(LSTM(lstm_out, dropout=0.2, recurrent_dropout=0.4))
model.add(Dense(1,activation='sigmoid'))
adam = tensorflow.keras.optimizers.Adam(learning_rate=0.002)
model.compile(loss = 'binary_crossentropy', optimizer=adam ,metrics = ['accuracy'])
print(model.summary())

In [ ]:
batch_size=16
model.fit(train_valid, y_train_valid, epochs = 3, batch_size=batch_size, validation_data =(test_valid, y_test_valid) , verbose = 'auto')

In [ ]:
y_pred = model.predict(X_test)

threshold =0.5
y_pred = np.where(y_pred > threshold, 1, 0)
y_pred = pd.DataFrame(y_pred)
y_pred.columns = ['target']
submission = pd.DataFrame(test.id)
submission['target'] = y_pred
submission = submission.set_index('id')
submission.target.value_counts()

In [ ]:
submission.to_csv("submission.csv")

# Third Submission Kaggle Score: 0.77137